name: nlp-light
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pytorch::pytorch=2.0.0  # macOS 전용 빌드 명시적 지정
  - cpuonly  # CPU 전용 모드 활성화
  - requests=2.28.1
  - beautifulsoup4=4.11.1
  - scikit-learn=1.2.0
  - pandas=1.5.2
  - numpy=1.24.1
  - pip=22.3.1
  - pip:
      - transformers==4.26.1
      - accelerate==0.19.0
      - sentencepiece==0.1.98